version: "3.8"

services:
  postgres:
    image: postgres:17.3-alpine3.21
    container_name: postgres-invest
    ports:
      - "5440:5432"  # Хост:5440 -> Контейнер:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "GGzS6AJHsArdm_tSn_H0"
      POSTGRES_DB: "invest-db"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d invest-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - invest-network

  invest-back:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy  # Ждем пока PostgreSQL будет готов
    ports:
      - "3030:3030"
    environment:
      DATABASE_URL: "postgresql://postgres:GGzS6AJHsArdm_tSn_H0@postgres:5432/invest-db?schema=public"
      JWT_SECRET: "your-secret-key-min-32-chars-change-me"
      JWT_EXPIRATION: "7d"
      PORT: 3030
      NODE_ENV: "production"
      CORS_ORIGIN: "http://192.168.1.86:3000"
      TOKEN_TINKOFF: "t.LGtqAIrqzVIGuafWs3vp2x7QVGyFZAkJRqbs0b1OCO9FhAjd4Qw6fT_uGSbm-bQj3ZoATIqp2zWpmym59FCcwg"
    networks:
      - invest-network

  invest-front:
    build:
      context: ../invest-front
      dockerfile: Dockerfile  # явно указываем Dockerfile (опционально)
    container_name: invest-front
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      # Если фронтенд обращается к бекенду через браузер (клиентская часть)
      REACT_APP_API_URL: "http://192.168.1.86:3030/api"
      # Если фронтенд обращается к бекенду на серверной стороне (SSR)
      API_URL: "http://invest-back:3030/api"
    depends_on:
      - invest-back
    restart: unless-stopped
    networks:
      - invest-network

volumes:
  postgres_data:

networks:
  invest-network:
    driver: bridge
